apiVersion: v1
kind: Service
metadata:
  name: devcontainer-nodeport
  namespace: keycloak
spec:
  type: NodePort
  ports:
  - name: keycloak-service
    nodePort: 30692
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: sx-keycloak
  sessionAffinity: None
